-- Additive controlled-record kinds only. This migration inserts no business or demo data.
ALTER TYPE "ManufacturingControlRecordKind" ADD VALUE IF NOT EXISTS 'TOOLS_DIES_MOULDS';
ALTER TYPE "ManufacturingControlRecordKind" ADD VALUE IF NOT EXISTS 'APPROVAL_WORKFLOW';
ALTER TYPE "ManufacturingControlRecordKind" ADD VALUE IF NOT EXISTS 'USER_ACCESS_REVIEW';
ALTER TYPE "ManufacturingControlRecordKind" ADD VALUE IF NOT EXISTS 'ELECTRONIC_SIGNATURE_POLICY';
ALTER TYPE "ManufacturingControlRecordKind" ADD VALUE IF NOT EXISTS 'STATUS_CONFIGURATION';
ALTER TYPE "ManufacturingControlRecordKind" ADD VALUE IF NOT EXISTS 'ALERT_NOTIFICATION_RULE';
ALTER TYPE "ManufacturingControlRecordKind" ADD VALUE IF NOT EXISTS 'PRINT_TEMPLATE';
ALTER TYPE "ManufacturingControlRecordKind" ADD VALUE IF NOT EXISTS 'INTEGRATION_SETTING';
ALTER TYPE "ManufacturingControlRecordKind" ADD VALUE IF NOT EXISTS 'ENVIRONMENT_UTILITY_CHECK';
ALTER TYPE "ManufacturingControlRecordKind" ADD VALUE IF NOT EXISTS 'QUALITY_CASE';
ALTER TYPE "ManufacturingControlRecordKind" ADD VALUE IF NOT EXISTS 'COMPLIANCE_RECORD';
ALTER TYPE "ManufacturingControlRecordKind" ADD VALUE IF NOT EXISTS 'RECALL_DRILL';
ALTER TYPE "ManufacturingControlRecordKind" ADD VALUE IF NOT EXISTS 'DATA_RETENTION_POLICY';
ALTER TYPE "ManufacturingControlRecordKind" ADD VALUE IF NOT EXISTS 'VALIDATION_DOCUMENT';
ALTER TYPE "ManufacturingControlRecordKind" ADD VALUE IF NOT EXISTS 'AUDIT_EVIDENCE_PACK';
ALTER TYPE "ManufacturingControlRecordKind" ADD VALUE IF NOT EXISTS 'EXECUTION_EVIDENCE';
