"use client";

import * as React from "react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { ArrowLeft, Banknote, CheckCircle2, FilePlus2, PackageCheck, Plus, Save, Ship, Trash2 } from "lucide-react";
import {
  useBankAccounts,
  useCreateLc,
  useCreateLcCostHead,
  useItems,
  useLc,
  useLcCommand,
  useLcCostHeads,
  useLcDashboard,
  useLcs,
  useMe,
  useParties,
  useWarehouses,
} from "@bizovix/api-client";
import type { LcItemRecord, Permission, SaveLcInput } from "@bizovix/types";
import { FormField, PrimaryButton, SecondaryButton, SelectInput, TextInput } from "@bizovix/ui";
import { useSetBreadcrumb } from "@/components/providers/BreadcrumbContext";

const today = () => new Date().toISOString().slice(0, 10);
const money = (value: string | number | null | undefined) => Number(value ?? 0).toLocaleString("en-US", { minimumFractionDigits: 2, maximumFractionDigits: 2 });
const statusLabel = (value: string) => value.replaceAll("_", " ");
const inputClass = "w-full rounded-md border border-biz-border bg-white px-3 py-2 text-sm text-biz-text outline-none focus:border-biz-blue";

function Notice({ value }: { value: string | null }) {
  if (!value) return null;
  return <div className="rounded-md border border-blue-200 bg-blue-50 px-4 py-2 text-sm text-biz-blue">{value}</div>;
}

function usePermissions() {
  const me = useMe();
  const permissions = me.data?.permissions ?? [];
  return (permission: Permission) => permissions.includes(permission);
}

export function LcRegisterWorkspace() {
  useSetBreadcrumb([{ label: "LC Management" }, { label: "LC Register" }]);
  const dashboard = useLcDashboard(), lcs = useLcs(), can = usePermissions();
  const [search, setSearch] = React.useState("");
  const rows = (lcs.data ?? []).filter((row) => `${row.lcNumber} ${row.supplierName} ${row.status}`.toLowerCase().includes(search.toLowerCase()));
  return <div className="space-y-4">
    <div className="flex flex-wrap items-start justify-between gap-3"><div><h1 className="text-page-title text-biz-text">LC Management</h1><p className="mt-1 text-sm text-biz-muted">Letters of credit, shipments, landed cost and inventory posting</p></div>{can("lc.create") && <Link href="/lc-management/create" className="inline-flex items-center gap-2 rounded-md bg-biz-blue px-4 py-2 text-sm font-semibold text-white"><FilePlus2 className="h-4 w-4" /> Open New LC</Link>}</div>
    <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{[["Total LC", dashboard.data?.total ?? 0], ["Draft", dashboard.data?.draft ?? 0], ["Active", dashboard.data?.active ?? 0], ["Finalized", dashboard.data?.finalized ?? 0]].map(([label, value]) => <div key={label} className="rounded-lg border border-biz-border bg-white p-4 shadow-card"><p className="text-xs font-semibold text-biz-muted">{label}</p><p className="mt-2 text-2xl font-bold text-biz-text">{value}</p></div>)}</div>
    <div className="grid gap-3 sm:grid-cols-2"><div className="rounded-lg border border-biz-border bg-white p-4"><p className="text-xs text-biz-muted">Total Purchase Value</p><p className="mt-1 text-xl font-bold">৳ {money(dashboard.data?.purchaseValue)}</p></div><div className="rounded-lg border border-biz-border bg-white p-4"><p className="text-xs text-biz-muted">Finalized Landed Value</p><p className="mt-1 text-xl font-bold">৳ {money(dashboard.data?.landedValue)}</p></div></div>
    <section className="rounded-lg border border-biz-border bg-white shadow-card"><div className="flex flex-wrap items-center justify-between gap-3 border-b border-biz-border p-4"><h2 className="font-bold">LC Register</h2><TextInput value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search LC or supplier" className="max-w-xs" /></div><div className="overflow-x-auto"><table className="w-full min-w-[900px] text-left text-xs"><thead className="bg-biz-bg"><tr>{["LC Number", "Date", "Supplier", "Payment", "Items", "Status", "Landed Cost", "Action"].map((label) => <th key={label} className="px-4 py-3">{label}</th>)}</tr></thead><tbody>{lcs.isLoading ? <tr><td colSpan={8} className="p-8 text-center text-biz-muted">Loading LC register...</td></tr> : !rows.length ? <tr><td colSpan={8} className="p-8 text-center text-biz-muted">No LC found.</td></tr> : rows.map((row) => <tr key={row.id} className="border-t border-biz-border"><td className="px-4 py-3 font-semibold">{row.lcNumber}</td><td className="px-4 py-3">{new Date(row.lcDate).toLocaleDateString()}</td><td className="px-4 py-3">{row.supplierName}</td><td className="px-4 py-3">{statusLabel(row.purchasePaymentStatus)}</td><td className="px-4 py-3">{row._count?.items ?? 0}</td><td className="px-4 py-3">{statusLabel(row.status)}</td><td className="px-4 py-3 text-right">{row.landedCost ? money(row.landedCost.landedCostTotal) : "—"}</td><td className="px-4 py-3"><Link className="font-semibold text-biz-blue hover:underline" href={`/lc-management/${row.id}`}>Open</Link></td></tr>)}</tbody></table></div></section>
  </div>;
}

type DraftItem = { itemId: string; productName: string; unit: string; quantity: string; foreignUnitPrice: string; weight: string; cbm: string; hsCode: string };
const emptyItem = (): DraftItem => ({ itemId: "", productName: "", unit: "pcs", quantity: "1", foreignUnitPrice: "0", weight: "", cbm: "", hsCode: "" });

export function LcCreateWorkspace() {
  useSetBreadcrumb([{ label: "LC Management", href: "/lc-management" }, { label: "Open New LC" }]);
  const router = useRouter(), create = useCreateLc(), suppliers = useParties({ roles: "SUPPLIER,VENDOR", status: "ACTIVE", limit: 200 }), warehouses = useWarehouses(), bankAccounts = useBankAccounts(), itemMasters = useItems({ status: "ACTIVE", limit: 200 });
  const [notice, setNotice] = React.useState<string | null>(null);
  const [form, setForm] = React.useState({ lcNumber: "", lcDate: today(), supplierId: "", supplierName: "", currency: "USD", exchangeRate: "", destinationWarehouseId: "", purchasePaymentStatus: "UNPAID", purchasePaidAmount: "0", bankAccountId: "", paymentReference: "", bankName: "", incoterm: "", originCountry: "", expiryDate: "", remarks: "" });
  const [items, setItems] = React.useState<DraftItem[]>([emptyItem()]);
  const total = items.reduce((sum, row) => sum + Number(row.quantity || 0) * Number(row.foreignUnitPrice || 0) * Number(form.exchangeRate || 0), 0);
  function updateItem(index: number, values: Partial<DraftItem>) { setItems((current) => current.map((row, rowIndex) => rowIndex === index ? { ...row, ...values } : row)); }
  async function submit(event: React.FormEvent) {
    event.preventDefault();
    const paid = form.purchasePaymentStatus === "PAID" ? total : Number(form.purchasePaidAmount || 0);
    const payload: SaveLcInput & Record<string, unknown> = { lcNumber: form.lcNumber || undefined, lcDate: form.lcDate, supplierId: form.supplierId || undefined, supplierName: form.supplierName, currency: form.currency, exchangeRate: Number(form.exchangeRate), destinationWarehouseId: form.destinationWarehouseId || undefined, purchasePaymentStatus: form.purchasePaymentStatus, purchasePaidAmount: paid, paymentAllocations: paid > 0 ? [{ accountId: form.bankAccountId, amount: paid, reference: form.paymentReference || undefined }] : [], bankName: form.bankName || undefined, incoterm: form.incoterm || undefined, originCountry: form.originCountry || undefined, expiryDate: form.expiryDate || undefined, remarks: form.remarks || undefined, items: items.map((row) => ({ itemId: row.itemId || undefined, productName: row.productName, unit: row.unit, quantity: Number(row.quantity), foreignUnitPrice: Number(row.foreignUnitPrice), weight: row.weight ? Number(row.weight) : undefined, cbm: row.cbm ? Number(row.cbm) : undefined, hsCode: row.hsCode || undefined })) };
    try { const saved = await create.mutateAsync(payload); router.push(`/lc-management/${saved.id}`); }
    catch (error) { setNotice(error instanceof Error ? error.message : "Could not create LC."); }
  }
  return <form onSubmit={submit} className="space-y-4">
    <div className="flex items-start justify-between gap-3"><div><h1 className="text-page-title text-biz-text">Open New LC</h1><p className="mt-1 text-sm text-biz-muted">Create purchase position and its balanced accounting entry</p></div><Link href="/lc-management" className="inline-flex items-center gap-2 text-sm font-semibold text-biz-blue"><ArrowLeft className="h-4 w-4" /> Back</Link></div><Notice value={notice} />
    <section className="rounded-lg border border-biz-border bg-white p-4 shadow-card"><h2 className="font-bold">LC & Supplier</h2><div className="mt-4 grid gap-3 md:grid-cols-3 xl:grid-cols-4"><FormField label="LC Number"><TextInput value={form.lcNumber} onChange={(event) => setForm({ ...form, lcNumber: event.target.value.toUpperCase() })} placeholder="Auto generated" /></FormField><FormField label="LC Date" required><TextInput type="date" value={form.lcDate} onChange={(event) => setForm({ ...form, lcDate: event.target.value })} required /></FormField><FormField label="Supplier" required><SelectInput value={form.supplierId} onChange={(event) => { const supplier = suppliers.data?.items.find((row) => row.id === event.target.value); setForm({ ...form, supplierId: event.target.value, supplierName: supplier?.name ?? "" }); }} options={(suppliers.data?.items ?? []).map((row) => ({ value: row.id, label: `${row.code} - ${row.name}` }))} placeholder="Select supplier" required /></FormField><FormField label="Destination Warehouse"><SelectInput value={form.destinationWarehouseId} onChange={(event) => setForm({ ...form, destinationWarehouseId: event.target.value })} options={(warehouses.data ?? []).filter((row) => row.isActive).map((row) => ({ value: row.id, label: `${row.code} - ${row.name}` }))} placeholder="Select warehouse" /></FormField><FormField label="Currency" required><TextInput value={form.currency} onChange={(event) => setForm({ ...form, currency: event.target.value.toUpperCase() })} required /></FormField><FormField label="Exchange Rate" required><TextInput type="number" min="0.0001" step="0.0001" value={form.exchangeRate} onChange={(event) => setForm({ ...form, exchangeRate: event.target.value })} required /></FormField><FormField label="Opening Bank"><TextInput value={form.bankName} onChange={(event) => setForm({ ...form, bankName: event.target.value })} /></FormField><FormField label="Incoterm"><TextInput value={form.incoterm} onChange={(event) => setForm({ ...form, incoterm: event.target.value.toUpperCase() })} /></FormField><FormField label="Origin Country"><TextInput value={form.originCountry} onChange={(event) => setForm({ ...form, originCountry: event.target.value })} /></FormField><FormField label="Expiry Date"><TextInput type="date" value={form.expiryDate} onChange={(event) => setForm({ ...form, expiryDate: event.target.value })} /></FormField></div></section>
    <section className="rounded-lg border border-biz-border bg-white p-4 shadow-card"><div className="flex items-center justify-between"><h2 className="font-bold">Products</h2><SecondaryButton type="button" size="sm" onClick={() => setItems([...items, emptyItem()])}><Plus className="h-4 w-4" /> Add Product</SecondaryButton></div><div className="mt-3 space-y-3">{items.map((row, index) => <div key={index} className="grid gap-2 rounded-md border border-biz-border p-3 md:grid-cols-6"><FormField label="Inventory Item"><SelectInput value={row.itemId} onChange={(event) => { const item = itemMasters.data?.items.find((candidate) => candidate.id === event.target.value); updateItem(index, { itemId: event.target.value, productName: item?.itemName ?? row.productName, unit: item?.uom?.symbol ?? item?.uom?.code ?? row.unit }); }} options={(itemMasters.data?.items ?? []).map((item) => ({ value: item.id, label: `${item.itemCode} - ${item.itemName}` }))} placeholder="Optional mapping" /></FormField><FormField label="Product Name" required><TextInput value={row.productName} onChange={(event) => updateItem(index, { productName: event.target.value })} required /></FormField><FormField label="Unit"><TextInput value={row.unit} onChange={(event) => updateItem(index, { unit: event.target.value })} /></FormField><FormField label="Quantity" required><TextInput type="number" min="0.0001" step="0.0001" value={row.quantity} onChange={(event) => updateItem(index, { quantity: event.target.value })} required /></FormField><FormField label={`Unit Price (${form.currency})`} required><TextInput type="number" min="0" step="0.0001" value={row.foreignUnitPrice} onChange={(event) => updateItem(index, { foreignUnitPrice: event.target.value })} required /></FormField><div className="flex items-end gap-2"><span className="pb-2 text-xs font-semibold">৳ {money(Number(row.quantity) * Number(row.foreignUnitPrice) * Number(form.exchangeRate))}</span>{items.length > 1 && <button type="button" className="mb-1 rounded p-2 text-red-600" onClick={() => setItems(items.filter((_, rowIndex) => rowIndex !== index))}><Trash2 className="h-4 w-4" /></button>}</div></div>)}</div><div className="mt-4 text-right text-lg font-bold">Purchase Total: ৳ {money(total)}</div></section>
    <section className="rounded-lg border border-biz-border bg-white p-4 shadow-card"><h2 className="font-bold">Purchase Payment</h2><div className="mt-4 grid gap-3 md:grid-cols-4"><FormField label="Payment Status"><SelectInput value={form.purchasePaymentStatus} onChange={(event) => setForm({ ...form, purchasePaymentStatus: event.target.value, purchasePaidAmount: event.target.value === "PAID" ? String(total) : event.target.value === "UNPAID" ? "0" : form.purchasePaidAmount })} options={[{ value: "UNPAID", label: "Unpaid / Credit" }, { value: "PARTIAL", label: "Partially Paid" }, { value: "PAID", label: "Paid in Full" }]} /></FormField>{form.purchasePaymentStatus !== "UNPAID" && <><FormField label="Paid Amount" required><TextInput type="number" min="0.01" max={total} step="0.01" value={form.purchasePaymentStatus === "PAID" ? String(total) : form.purchasePaidAmount} disabled={form.purchasePaymentStatus === "PAID"} onChange={(event) => setForm({ ...form, purchasePaidAmount: event.target.value })} required /></FormField><FormField label="Paid From" required><SelectInput value={form.bankAccountId} onChange={(event) => setForm({ ...form, bankAccountId: event.target.value })} options={(bankAccounts.data ?? []).map((row) => ({ value: row.id, label: row.accountName }))} placeholder="Select account" required /></FormField><FormField label="Reference"><TextInput value={form.paymentReference} onChange={(event) => setForm({ ...form, paymentReference: event.target.value })} /></FormField></>}</div></section>
    <FormField label="Remarks"><textarea className={inputClass} rows={3} value={form.remarks} onChange={(event) => setForm({ ...form, remarks: event.target.value })} /></FormField><div className="flex justify-end"><PrimaryButton type="submit" disabled={create.isPending}><Save className="h-4 w-4" /> {create.isPending ? "Creating..." : "Create LC & Post"}</PrimaryButton></div>
  </form>;
}

export function LcCostHeadsWorkspace() {
  useSetBreadcrumb([{ label: "LC Management", href: "/lc-management" }, { label: "Cost Heads" }]);
  const heads = useLcCostHeads(), create = useCreateLcCostHead(), command = useLcCommand<{ id: string; success: boolean }>(), can = usePermissions();
  const [notice, setNotice] = React.useState<string | null>(null), [form, setForm] = React.useState({ name: "", code: "", category: "OTHER", defaultAllocationMethod: "PURCHASE_VALUE", includeInLandedCost: true });
  async function save(event: React.FormEvent) { event.preventDefault(); try { await create.mutateAsync(form); setForm({ ...form, name: "", code: "" }); setNotice("LC cost head created."); } catch (error) { setNotice(error instanceof Error ? error.message : "Could not create cost head."); } }
  async function remove(id: string) { if (!window.confirm("Delete this unused custom cost head?")) return; try { await command.mutateAsync({ path: `cost-heads/${id}`, method: "DELETE" }); setNotice("Cost head deleted."); } catch (error) { setNotice(error instanceof Error ? error.message : "Could not delete cost head."); } }
  return <div className="space-y-4"><div><h1 className="text-page-title text-biz-text">LC Cost Heads</h1><p className="mt-1 text-sm text-biz-muted">Allocation defaults and landed-cost categories</p></div><Notice value={notice} />{can("lc.configure") && <form onSubmit={save} className="grid gap-3 rounded-lg border border-biz-border bg-white p-4 md:grid-cols-5"><FormField label="Name" required><TextInput value={form.name} onChange={(event) => setForm({ ...form, name: event.target.value })} required /></FormField><FormField label="Code"><TextInput value={form.code} onChange={(event) => setForm({ ...form, code: event.target.value.toUpperCase() })} /></FormField><FormField label="Category"><SelectInput value={form.category} onChange={(event) => setForm({ ...form, category: event.target.value })} options={["LC_BANKING", "ORIGIN", "FREIGHT", "INSURANCE", "CUSTOMS", "TAX", "CNF", "PORT", "DESTINATION_TRANSPORT", "LOCAL", "OTHER"].map((value) => ({ value, label: statusLabel(value) }))} /></FormField><FormField label="Allocation"><SelectInput value={form.defaultAllocationMethod} onChange={(event) => setForm({ ...form, defaultAllocationMethod: event.target.value })} options={["PURCHASE_VALUE", "USD_VALUE", "QUANTITY", "WEIGHT", "CBM", "EQUAL"].map((value) => ({ value, label: statusLabel(value) }))} /></FormField><div className="flex items-end"><PrimaryButton type="submit"><Plus className="h-4 w-4" /> Add Head</PrimaryButton></div></form>}<div className="overflow-x-auto rounded-lg border border-biz-border bg-white"><table className="w-full min-w-[760px] text-left text-xs"><thead className="bg-biz-bg"><tr>{["Code", "Name", "Category", "Default Allocation", "Landed Cost", "Usage", "Action"].map((label) => <th key={label} className="px-4 py-3">{label}</th>)}</tr></thead><tbody>{(heads.data ?? []).map((row) => <tr key={row.id} className="border-t border-biz-border"><td className="px-4 py-3 font-semibold">{row.code}</td><td className="px-4 py-3">{row.name}</td><td className="px-4 py-3">{statusLabel(row.category)}</td><td className="px-4 py-3">{statusLabel(row.defaultAllocationMethod)}</td><td className="px-4 py-3">{row.includeInLandedCost ? "Included" : "Excluded"}</td><td className="px-4 py-3">{row._count?.costEntries ?? 0}</td><td className="px-4 py-3">{can("lc.configure") && !row.isSystem && !(row._count?.costEntries) && <button className="text-red-600" onClick={() => remove(row.id)}>Delete</button>}</td></tr>)}</tbody></table></div></div>;
}

export function LcDetailWorkspace({ id }: { id: string }) {
  const lc = useLc(id), heads = useLcCostHeads(), warehouses = useWarehouses(), bankAccounts = useBankAccounts(), itemMasters = useItems({ status: "ACTIVE", limit: 200 }), command = useLcCommand(), can = usePermissions();
  const [notice, setNotice] = React.useState<string | null>(null), [show, setShow] = React.useState<"shipment" | "cost" | "grn" | "payment" | null>(null);
  const [shipment, setShipment] = React.useState({ transportMode: "SEA", shipmentNumber: "", blAwbNumber: "", eta: "", containerNumber: "" });
  const [cost, setCost] = React.useState({ costHeadId: "", vendorName: "", invoiceNumber: "", invoiceDate: today(), bdtAmount: "", allocationBasis: "PURCHASE_VALUE", paymentMethod: "CREDIT", bankAccountId: "" });
  const [payment, setPayment] = React.useState({ purchasePaymentStatus: "PAID", purchasePaidAmount: "", bankAccountId: "", reference: "" });
  useSetBreadcrumb([{ label: "LC Management", href: "/lc-management" }, { label: lc.data?.lcNumber ?? "LC Detail" }]);
  async function act(path: string, body?: unknown, method: "POST" | "PATCH" | "DELETE" = "POST", success = "Saved.") { try { await command.mutateAsync({ path, method, body }); setNotice(success); setShow(null); } catch (error) { setNotice(error instanceof Error ? error.message : "Action failed."); } }
  if (lc.isLoading) return <div className="p-8 text-center text-biz-muted">Loading LC...</div>;
  if (!lc.data) return <div className="rounded-lg border border-biz-border bg-white p-8 text-center">LC not found.</div>;
  const row = lc.data, purchaseTotal = row.items.reduce((sum, item) => sum + Number(item.totalPurchaseCostBdt), 0), editable = !["FINALIZED", "CLOSED", "CANCELLED"].includes(row.status);
  const remainingItems = row.items.filter((item) => Number(item.receivedQuantity) < Number(item.quantity));
  async function saveShipment(event: React.FormEvent) { event.preventDefault(); await act(`${id}/shipments`, { ...shipment, eta: shipment.eta || undefined, shipmentNumber: shipment.shipmentNumber || undefined, blAwbNumber: shipment.blAwbNumber || undefined, containerNumber: shipment.containerNumber || undefined }, "POST", "Shipment added."); }
  async function saveCost(event: React.FormEvent) { event.preventDefault(); const amount = Number(cost.bdtAmount); await act(`${id}/cost-entries`, { costHeadId: cost.costHeadId, vendorName: cost.vendorName || undefined, invoiceNumber: cost.invoiceNumber || undefined, invoiceDate: cost.invoiceDate, currency: "BDT", bdtAmount: amount, allocationMode: "AUTO", allocationBasis: cost.allocationBasis, paymentMethod: cost.paymentMethod, creditPayeeName: cost.paymentMethod === "CREDIT" ? cost.vendorName : undefined, paymentAllocations: cost.paymentMethod === "CASH_BANK_MFS" ? [{ accountId: cost.bankAccountId, amount }] : [] }, "POST", "Cost posted and allocated."); }
  async function savePayment(event: React.FormEvent) { event.preventDefault(); const paid = payment.purchasePaymentStatus === "PAID" ? purchaseTotal : Number(payment.purchasePaidAmount); await act(id, { purchasePaymentStatus: payment.purchasePaymentStatus, purchasePaidAmount: paid, paymentAllocations: paid > 0 ? [{ accountId: payment.bankAccountId, amount: paid, reference: payment.reference || undefined }] : [] }, "PATCH", "Purchase payment position updated."); }
  async function receiveAll() { await act(`${id}/grns`, { receivedDate: today(), warehouseId: row.destinationWarehouseId || undefined, items: remainingItems.map((item) => ({ lcItemId: item.id, receivedQuantity: Number(item.quantity) - Number(item.receivedQuantity) })) }, "POST", "GRN recorded."); }
  async function finalize() { await act(`${id}/landed-cost/finalize`, undefined, "POST", "Landed cost finalized and accounting posted."); }
  async function postInventory() { const warehouseId = row.destinationWarehouseId || warehouses.data?.find((warehouse) => warehouse.isActive)?.id; if (!warehouseId) { setNotice("Select or create an active destination warehouse first."); return; } await act(`${id}/landed-cost/post-inventory`, { items: row.items.filter((item) => !item.inventoryPosting).map((item) => ({ lcItemId: item.id, warehouseId, itemId: item.itemId || undefined, postingType: item.itemId ? "EXISTING" : "NEW" })) }, "POST", "Inventory receipt posted."); }
  async function reopen() { const reason = window.prompt("Reason for reopening finalized landed cost"); if (reason) await act(`${id}/landed-cost/reopen`, { reason }, "POST", "LC reopened; accounting and stock postings reversed."); }
  return <div className="space-y-4">
    <div className="flex flex-wrap items-start justify-between gap-3"><div><Link href="/lc-management" className="mb-2 inline-flex items-center gap-1 text-xs font-semibold text-biz-blue"><ArrowLeft className="h-3.5 w-3.5" /> LC Register</Link><h1 className="text-page-title text-biz-text">{row.lcNumber}</h1><p className="mt-1 text-sm text-biz-muted">{row.supplierName} · {statusLabel(row.status)}</p></div><div className="flex flex-wrap gap-2">{editable && can("lc.edit") && <><SecondaryButton onClick={() => setShow(show === "shipment" ? null : "shipment")}><Ship className="h-4 w-4" /> Shipment</SecondaryButton><SecondaryButton onClick={() => setShow(show === "grn" ? null : "grn")}><PackageCheck className="h-4 w-4" /> Receive GRN</SecondaryButton><SecondaryButton onClick={() => setShow(show === "payment" ? null : "payment")}><Banknote className="h-4 w-4" /> Payment</SecondaryButton></>}{editable && can("lc.cost.enter") && <PrimaryButton onClick={() => setShow(show === "cost" ? null : "cost")}><Plus className="h-4 w-4" /> Add Cost</PrimaryButton>}</div></div><Notice value={notice} />
    <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-5">{[["Purchase", `৳ ${money(purchaseTotal)}`], ["Paid", `৳ ${money(row.purchasePaidAmount)}`], ["Import Cost", `৳ ${money(row.costEntries.reduce((sum, entry) => sum + Number(entry.bdtAmount), 0))}`], ["Landed Cost", row.landedCost ? `৳ ${money(row.landedCost.landedCostTotal)}` : "Not finalized"], ["Inventory", `${row.items.filter((item) => item.inventoryPosting).length}/${row.items.length} posted`]].map(([label, value]) => <div key={label} className="rounded-lg border border-biz-border bg-white p-4"><p className="text-xs text-biz-muted">{label}</p><p className="mt-1 font-bold">{value}</p></div>)}</div>
    {show === "shipment" && <form onSubmit={saveShipment} className="grid gap-3 rounded-lg border border-biz-border bg-white p-4 md:grid-cols-5"><FormField label="Mode"><SelectInput value={shipment.transportMode} onChange={(event) => setShipment({ ...shipment, transportMode: event.target.value })} options={["SEA", "AIR", "ROAD", "RAIL", "COURIER", "MULTIMODAL"].map((value) => ({ value, label: value }))} /></FormField><FormField label="Shipment No"><TextInput value={shipment.shipmentNumber} onChange={(event) => setShipment({ ...shipment, shipmentNumber: event.target.value })} /></FormField><FormField label="BL / AWB"><TextInput value={shipment.blAwbNumber} onChange={(event) => setShipment({ ...shipment, blAwbNumber: event.target.value })} /></FormField><FormField label="ETA"><TextInput type="date" value={shipment.eta} onChange={(event) => setShipment({ ...shipment, eta: event.target.value })} /></FormField><div className="flex items-end"><PrimaryButton type="submit">Save Shipment</PrimaryButton></div></form>}
    {show === "cost" && <form onSubmit={saveCost} className="grid gap-3 rounded-lg border border-biz-border bg-white p-4 md:grid-cols-4 xl:grid-cols-7"><FormField label="Cost Head" required><SelectInput value={cost.costHeadId} onChange={(event) => { const head = heads.data?.find((candidate) => candidate.id === event.target.value); setCost({ ...cost, costHeadId: event.target.value, allocationBasis: head?.defaultAllocationMethod ?? cost.allocationBasis }); }} options={(heads.data ?? []).filter((head) => head.isActive).map((head) => ({ value: head.id, label: head.name }))} required /></FormField><FormField label="Vendor / Payee"><TextInput value={cost.vendorName} onChange={(event) => setCost({ ...cost, vendorName: event.target.value })} /></FormField><FormField label="Invoice No"><TextInput value={cost.invoiceNumber} onChange={(event) => setCost({ ...cost, invoiceNumber: event.target.value })} /></FormField><FormField label="Invoice Date"><TextInput type="date" value={cost.invoiceDate} onChange={(event) => setCost({ ...cost, invoiceDate: event.target.value })} /></FormField><FormField label="BDT Amount" required><TextInput type="number" min="0.01" step="0.01" value={cost.bdtAmount} onChange={(event) => setCost({ ...cost, bdtAmount: event.target.value })} required /></FormField><FormField label="Payment"><SelectInput value={cost.paymentMethod} onChange={(event) => setCost({ ...cost, paymentMethod: event.target.value })} options={[{ value: "CREDIT", label: "Credit / Payable" }, { value: "CASH_BANK_MFS", label: "Cash / Bank" }]} /></FormField>{cost.paymentMethod === "CASH_BANK_MFS" && <FormField label="Paid From" required><SelectInput value={cost.bankAccountId} onChange={(event) => setCost({ ...cost, bankAccountId: event.target.value })} options={(bankAccounts.data ?? []).map((account) => ({ value: account.id, label: account.accountName }))} required /></FormField>}<div className="flex items-end"><PrimaryButton type="submit">Post & Allocate</PrimaryButton></div></form>}
    {show === "payment" && <form onSubmit={savePayment} className="grid gap-3 rounded-lg border border-biz-border bg-white p-4 md:grid-cols-5"><FormField label="Status"><SelectInput value={payment.purchasePaymentStatus} onChange={(event) => setPayment({ ...payment, purchasePaymentStatus: event.target.value })} options={[{ value: "UNPAID", label: "Unpaid" }, { value: "PARTIAL", label: "Partial" }, { value: "PAID", label: "Paid" }]} /></FormField>{payment.purchasePaymentStatus === "PARTIAL" && <FormField label="Paid Amount"><TextInput type="number" min="0.01" max={purchaseTotal - 0.01} value={payment.purchasePaidAmount} onChange={(event) => setPayment({ ...payment, purchasePaidAmount: event.target.value })} required /></FormField>}{payment.purchasePaymentStatus !== "UNPAID" && <><FormField label="Paid From"><SelectInput value={payment.bankAccountId} onChange={(event) => setPayment({ ...payment, bankAccountId: event.target.value })} options={(bankAccounts.data ?? []).map((account) => ({ value: account.id, label: account.accountName }))} required /></FormField><FormField label="Reference"><TextInput value={payment.reference} onChange={(event) => setPayment({ ...payment, reference: event.target.value })} /></FormField></>}<div className="flex items-end"><PrimaryButton type="submit">Update Payment</PrimaryButton></div></form>}
    {show === "grn" && <div className="rounded-lg border border-biz-border bg-white p-4"><p className="text-sm">This posts the remaining quantity for {remainingItems.length} product(s) to <b>{row.destinationWarehouse?.name ?? "the selected destination warehouse"}</b>.</p><div className="mt-3"><PrimaryButton onClick={receiveAll} disabled={!remainingItems.length}>Receive All Remaining</PrimaryButton></div></div>}
    <section className="rounded-lg border border-biz-border bg-white shadow-card"><div className="border-b border-biz-border p-4"><h2 className="font-bold">Products & Landed Cost</h2></div><div className="overflow-x-auto"><table className="w-full min-w-[900px] text-left text-xs"><thead className="bg-biz-bg"><tr>{["Product", "Qty", "Received", "Purchase Cost", "Landed / Unit", "Inventory Item", "Warehouse"].map((label) => <th key={label} className="px-4 py-3">{label}</th>)}</tr></thead><tbody>{row.items.map((item) => <tr key={item.id} className="border-t border-biz-border"><td className="px-4 py-3 font-semibold">{item.productName}</td><td className="px-4 py-3">{item.quantity} {item.unit}</td><td className="px-4 py-3">{item.receivedQuantity}</td><td className="px-4 py-3 text-right">{money(item.totalPurchaseCostBdt)}</td><td className="px-4 py-3 text-right">{item.landedCostPerUnit ? money(item.landedCostPerUnit) : "—"}</td><td className="px-4 py-3">{item.itemId ? itemMasters.data?.items.find((master) => master.id === item.itemId)?.itemName ?? "Mapped item" : "Will create on posting"}</td><td className="px-4 py-3">{item.inventoryPosting?.warehouse.name ?? "—"}</td></tr>)}</tbody></table></div></section>
    <div className="grid gap-4 xl:grid-cols-2"><section className="rounded-lg border border-biz-border bg-white p-4"><h2 className="font-bold">Import Costs</h2>{!row.costEntries.length ? <p className="mt-3 text-sm text-biz-muted">No import costs posted.</p> : row.costEntries.map((entry) => <div key={entry.id} className="mt-3 flex items-center justify-between gap-3 border-t border-biz-border pt-3 text-xs"><div><b>{entry.costHead.name}</b><p className="text-biz-muted">{entry.vendorName ?? "No payee"} · {statusLabel(entry.allocationBasis ?? entry.allocationMode)}</p></div><div className="flex items-center gap-3"><b>৳ {money(entry.bdtAmount)}</b>{editable && can("lc.cost.edit") && !entry.isLocked && <button className="text-red-600" onClick={() => act(`${id}/cost-entries/${entry.id}`, undefined, "DELETE", "Cost deleted and accounting reversed.")}><Trash2 className="h-4 w-4" /></button>}</div></div>)}</section><section className="rounded-lg border border-biz-border bg-white p-4"><h2 className="font-bold">Shipments & GRNs</h2>{row.shipments.map((entry) => <div key={entry.id} className="mt-3 border-t pt-3 text-xs"><b>{entry.shipmentNumber ?? entry.transportMode}</b> · {entry.blAwbNumber ?? "No BL/AWB"} · ETA {entry.eta ? new Date(entry.eta).toLocaleDateString() : "—"}</div>)}{row.grns.map((entry) => <div key={entry.id} className="mt-3 border-t pt-3 text-xs"><b>{entry.grnNumber}</b> · {new Date(entry.receivedDate).toLocaleDateString()} · {entry.warehouse?.name ?? "No warehouse"}</div>)}{!row.shipments.length && !row.grns.length && <p className="mt-3 text-sm text-biz-muted">No shipment or GRN recorded.</p>}</section></div>
    <section className="flex flex-wrap items-center justify-between gap-3 rounded-lg border border-biz-border bg-white p-4"><div><h2 className="font-bold">Finalization & Inventory</h2><p className="mt-1 text-xs text-biz-muted">Full purchase payment, received quantity and exact cost allocation are required.</p></div><div className="flex flex-wrap gap-2">{row.landedCost?.status === "FINALIZED" ? <>{can("lc.finalize") && row.items.some((item) => !item.inventoryPosting) && <PrimaryButton onClick={postInventory}><PackageCheck className="h-4 w-4" /> Post Inventory</PrimaryButton>}{can("lc.finalize.reopen") && row.status !== "CLOSED" && <SecondaryButton onClick={reopen}>Reopen</SecondaryButton>}</> : can("lc.finalize") && <PrimaryButton onClick={finalize}><CheckCircle2 className="h-4 w-4" /> Finalize Landed Cost</PrimaryButton>}{row.landedCost?.status === "FINALIZED" && row.items.every((item) => item.inventoryPosting) && row.status !== "CLOSED" && can("lc.edit") && <SecondaryButton onClick={() => act(`${id}/status`, { status: "CLOSED", reason: "Operational workflow completed" }, "PATCH", "LC closed.")}>Close LC</SecondaryButton>}</div></section>
  </div>;
}
