import { Banknote,BriefcaseBusiness,CalendarClock,FileChartColumn,Landmark,ReceiptText,WalletCards,type LucideIcon } from "lucide-react";
export interface ReportCardDef{slug:string;title:string;description:string}
export interface ReportCategoryDef{slug:string;title:string;shortTitle:string;icon:LucideIcon;reports:ReportCardDef[]}
export const REPORT_CATEGORIES:ReportCategoryDef[]=[
 {slug:"tenders",title:"Tender & Bank Instruments",shortTitle:"Tender Reports",icon:FileChartColumn,reports:[
  {slug:"summary",title:"Tender Summary",description:"Purchased tender status and value overview."},{slug:"performance",title:"Tender Performance",description:"Award rate and tender performance analysis."},{slug:"tender-security",title:"Tender Security",description:"Security amount, margin and expiry status."},{slug:"credit-commitment",title:"Credit Commitment",description:"Tender commitment charges by bank."},{slug:"pg-bg",title:"PG/BG Report",description:"Guarantee exposure, amount and expiry."},{slug:"organization",title:"Tender Organization",description:"Organization-wise tender activity."},{slug:"category",title:"Tender Category",description:"Work category-wise tender analysis."}]},
 {slug:"projects",title:"Projects & CMS",shortTitle:"Project Reports",icon:BriefcaseBusiness,reports:[
  {slug:"ongoing",title:"Ongoing Works",description:"Active project value, receipt and expense."},{slug:"archived",title:"Archived Works",description:"Completed project financial outcome."},{slug:"performance",title:"Project Performance",description:"Operational and financial progress."},{slug:"profitability",title:"Project Profitability",description:"Actual cost, profit and margin by project."},{slug:"organization",title:"Organization-wise Projects",description:"Projects grouped by client organization."},{slug:"category",title:"Category-wise Projects",description:"Projects grouped by work category."}]},
 {slug:"expenses",title:"Expenses",shortTitle:"Expense Reports",icon:WalletCards,reports:[
  {slug:"project",title:"Project Expense",description:"Detailed project-linked expenses."},{slug:"general",title:"General Expense",description:"Administrative and company expenses."},{slug:"category",title:"Expense by Category",description:"Category contribution and counts."},{slug:"person",title:"Expense by Person",description:"Person-wise expense accountability."},{slug:"account",title:"Expense by Payment Account",description:"Expense by source account."},{slug:"monthly",title:"Monthly Expense",description:"Month-wise expense movement."}]},
 {slug:"receipts",title:"Receipts",shortTitle:"Receipt Reports",icon:ReceiptText,reports:[
  {slug:"summary",title:"Receipt Summary",description:"Receipt totals and transaction details."},{slug:"project-wise",title:"Project-wise Receipts",description:"Collections against project contracts."},{slug:"organization",title:"Organization-wise Receipts",description:"Client organization collection summary."},{slug:"outstanding",title:"Outstanding Receivables",description:"Uncollected project contract values."},{slug:"monthly",title:"Monthly Receipt",description:"Month-wise receipt analysis."}]},
 {slug:"cash-bank",title:"Cash & Bank",shortTitle:"Cash & Bank Reports",icon:Landmark,reports:[
  {slug:"cash-book",title:"Cash Book",description:"Main and physical cash movements."},{slug:"petty-cash",title:"Petty Cash",description:"Small operational cash transactions."},{slug:"bank-book",title:"Bank Book",description:"Bank account debit and credit movements."},{slug:"bank-statement",title:"Bank Statement",description:"Account-wise running statement."},{slug:"transfers",title:"Bank Transfers",description:"Internal transfer history and charges."},{slug:"cheques",title:"Cheque Report",description:"Issued and received cheque lifecycle."},{slug:"reconciliation",title:"Reconciliation",description:"ERP and statement balance matching."}]},
 {slug:"financial",title:"Financial",shortTitle:"Financial Reports",icon:Banknote,reports:[
  {slug:"income-expense",title:"Income vs Expense",description:"Operational receipts versus expenses."},{slug:"cash-flow",title:"Cash Flow",description:"Management cash flow without transfer duplication."},{slug:"profitability",title:"Project Profitability",description:"Contract value, cost and expected margin."},{slug:"charges",title:"Financial Charges",description:"Tender and banking related charges."},{slug:"summary",title:"Financial Summary",description:"Consolidated financial position."}]},
 {slug:"expiry-due",title:"Expiry & Due",shortTitle:"Expiry & Due Reports",icon:CalendarClock,reports:[
  {slug:"tender-security",title:"Tender Security Expiry",description:"Security expiry and overdue list."},{slug:"pg-bg",title:"PG/BG Expiry",description:"Guarantees approaching expiry."},{slug:"receivables",title:"Receivable Due",description:"Outstanding project collections."},{slug:"payables",title:"Payable Due",description:"Upcoming expense liabilities."},{slug:"loan-emi",title:"Loan / EMI",description:"Loan and EMI due tracking."},{slug:"documents",title:"Document Expiry",description:"Business document expiry dates."},{slug:"cheques",title:"Pending Cheques",description:"Pending and deposited cheques."}]},
];
export const findReport=(category:string,report:string)=>REPORT_CATEGORIES.find(c=>c.slug===category)?.reports.find(r=>r.slug===report);
