export interface HrLookup { id: string; name: string; level?: number | null; }
export interface HrEmployee { id: string; employeeCode: string; name: string; phone: string | null; email: string | null; employmentType: string; status: string; joiningDate: string; grossSalary: string; pfRate: string | null; paymentMethod: string; department: HrLookup | null; designation: HrLookup | null; grade: HrLookup | null; businessUnit: HrLookup | null; division: HrLookup | null; location: HrLookup | null; costCenter: HrLookup | null; }
export interface HrAttendance { id: string; attendanceDate: string; status: string; checkIn: string | null; checkOut: string | null; lateMinutes: number; overtimeMinutes: number; workedMinutes: number; employee: Pick<HrEmployee, "id" | "employeeCode" | "name">; }
export interface HrPayslip { id: string; employeeId: string; employeeCode: string; employeeName: string; proratedGross: string; totalDeduction: string; netPayable: string; paymentStatus: string; }
export interface HrPayrollRun { id: string; periodYear: number; periodMonth: number; status: string; totalGross: string; totalDeduction: string; totalNetPayable: string; payslips: HrPayslip[]; }
export interface HrLeaveRequest { id: string; startDate: string; endDate: string; totalDays: string; status: string; reason: string | null; employee: Pick<HrEmployee, "id" | "employeeCode" | "name">; leaveType: HrLookup; }
export interface HrExpenseClaim { id: string; category: string; amount: string; expenseDate: string; status: string; employee: Pick<HrEmployee, "id" | "employeeCode" | "name">; }
export interface HrLoan { id: string; loanType: string; principalAmount: string; totalRepaid: string; remainingBalance: string; status: string; employee: Pick<HrEmployee, "id" | "employeeCode" | "name">; }
export interface HrJobOpening { id: string; title: string; status: string; numberOfPositions: number; department: HrLookup | null; designation: HrLookup | null; _count: { applications: number }; }
export interface SaveEmployeeInput { employeeCode?: string; name: string; departmentId?: string; designationId?: string; employmentType?: string; joiningDate: string; grossSalary: number; salaryComponents: Array<{ name: string; percent: number }>; pfRate?: number; paymentMethod?: string; phone?: string; email?: string; }
