export interface LcListRecord { id: string; lcNumber: string; lcDate: string; supplierName: string; currency: string; exchangeRate: string; purchasePaymentStatus: string; purchasePaidAmount: string; status: string; landedCost: { status: string; landedCostTotal: string } | null; _count?: { items: number; shipments: number; costEntries: number; grns: number }; }
export interface LcItemRecord { id: string; itemId: string | null; productName: string; unit: string; quantity: string; foreignUnitPrice: string; totalPurchaseCostBdt: string; receivedQuantity: string; landedCostPerUnit: string | null; suggestedSellingPrice?: string | null; inventoryPosting: { id: string; warehouse: { id: string; name: string } } | null; }
export interface LcShipmentRecord { id: string; transportMode: string; shipmentNumber: string | null; blAwbNumber: string | null; etd: string | null; eta: string | null; containerNumber: string | null; forwarderName: string | null; }
export interface LcCostEntryRecord { id: string; vendorName: string | null; invoiceNumber: string | null; invoiceDate: string | null; currency: string; bdtAmount: string; allocationMode: string; allocationBasis: string | null; includeInLandedCost: boolean; isAllocated: boolean; isLocked: boolean; paymentMethod: string | null; costHead: { id: string; name: string; category: string }; }
export interface LcGrnRecord { id: string; grnNumber: string; receivedDate: string; status: string; warehouse: { id: string; name: string } | null; items: Array<{ id: string; lcItemId: string; receivedQuantity: string; damagedQuantity: string; rejectedQuantity: string; lcItem: { productName: string } }>; }
export interface LcStatusHistoryRecord { id: string; fromStatus: string | null; toStatus: string; reason: string | null; changedAt: string; }
export interface LcLandedCostRecord { id: string; status: string; purchaseCostBdt: string; importCostBdt: string; landedCostTotal: string; finalizedAt: string | null; }
export interface LcDetail extends LcListRecord { supplierId?: string | null; supplier?: { id: string; code: string; name: string } | null; destinationWarehouseId?: string | null; destinationWarehouse?: WarehouseRecord | null; purchasePayable?: { id: string; amount: string; paidAmount: string; status: string } | null; paymentAllocations?: Array<{ accountId: string; amount: number; reference?: string }> | null; items: LcItemRecord[]; shipments: LcShipmentRecord[]; costEntries: LcCostEntryRecord[]; grns: LcGrnRecord[]; statusHistory: LcStatusHistoryRecord[]; landedCost: LcLandedCostRecord | null; }
export interface LcDashboard { total: number; draft: number; active: number; finalized: number; purchaseValue: string; landedValue: string; }
export interface WarehouseRecord { id: string; code: string; name: string; address: string | null; isActive: boolean; }
export interface LcCostHeadRecord { id: string; code: string; name: string; category: string; defaultAllocationMethod: string; fallbackAllocationMethod?: string; includeInLandedCost: boolean; manualOverrideAllowed?: boolean; isSystem?: boolean; isActive: boolean; _count?: { costEntries: number }; }
export interface SaveLcInput { lcNumber?: string; lcDate: string; supplierId?: string; supplierName: string; currency?: string; exchangeRate: number; purchasePaymentStatus?: string; purchasePaidAmount?: number; paymentAllocations?: Array<{ accountId: string; amount: number; reference?: string }>; destinationWarehouseId?: string; items: Array<{ itemId?: string; productName: string; unit?: string; quantity: number; foreignUnitPrice: number; acceptedBdtUnitPrice?: number; weight?: number; cbm?: number; hsCode?: string }>; }
