export const PERMISSIONS = [
  "dashboard.view",

  "document_purchase.create",
  "document_purchase.read",
  "document_purchase.update",
  "document_purchase.delete",
  "document_purchase.export",

  "tender_security.create",
  "tender_security.read",
  "tender_security.update",
  "tender_security.mark_not_required",

  "credit_commitment.create",
  "credit_commitment.read",
  "credit_commitment.update",
  "credit_commitment.delete",

  "pg_bg.read",
  "pg_bg.create",
  "pg_bg.update",
  "pg_bg.accept_noa",
  "pg_bg.save_draft",

  "cms.work.read",
  "cms.work.create",
  "cms.work.update",
  "cms.work.archive",
  "cms.work.export",
  "cms.work.restore",

  "expense.create",
  "expense.read",
  "expense.approve",

  "project_expense.read",
  "project_expense.create",
  "project_expense.update",
  "project_expense.delete",
  "project_expense.export",

  "receipt.create",
  "receipt.read",

  "cash_bank.read",
  "cash_bank.create",
  "bank_account.read",
  "bank_account.create",
  "bank_account.update",
  "bank_transfer.read",
  "bank_transfer.create",
  "financial_transaction.read",
  "financial_transaction.export",
  "bank_reconciliation.read",
  "bank_reconciliation.manage",
  "cheque.read",
  "cheque.create",
  "cheque.update",

  "accounts.read",
  "chart_of_accounts.read",
  "chart_of_accounts.create",
  "chart_of_accounts.update",
  "journal.read",
  "journal.create",
  "journal.post",
  "journal.reverse",
  "ledger.read",
  "receivable.read",
  "receivable.manage",
  "payable.read",
  "payable.manage",
  "project_accounts.read",
  "party_ledger.read",
  "opening_balance.read",
  "opening_balance.manage",

  "report.view",
  "report.export",

  "reminders.read",
  "reminders.create",
  "reminders.update",
  "reminders.complete",
  "reminders.cancel",

  "notifications.read",

  "user.manage",
  "role.manage",
  "settings.read",
  "settings.manage",

  "billing.view",
  "billing.manage",
  "billing.invoice.view",
] as const;

export type Permission = (typeof PERMISSIONS)[number];
