export const PERMISSIONS = [
  "dashboard.view",

  "tender.read",
  "tender.create",
  "tender.update",
  "tender.submit",
  "tender.result.manage",
  "tender.costing.read",
  "tender.costing.update",
  "tender.costing.approve",

  "document_purchase.create",
  "document_purchase.read",
  "document_purchase.update",
  "document_purchase.delete",
  "document_purchase.export",

  "tender_security.create",
  "tender_security.read",
  "tender_security.update",
  "tender_security.mark_not_required",

  "credit_commitment.create",
  "credit_commitment.read",
  "credit_commitment.update",
  "credit_commitment.delete",

  "pg_bg.read",
  "pg_bg.create",
  "pg_bg.update",
  "pg_bg.accept_noa",
  "pg_bg.save_draft",

  "cms.work.read",
  "cms.work.create",
  "cms.work.update",
  "cms.work.archive",
  "cms.work.export",
  "cms.work.restore",

  "contract.read",
  "contract.create",
  "contract.update",
  "contract.activate",

  "project_budget.read",
  "project_budget.create",
  "project_budget.approve",

  "boq.read",
  "boq.create",
  "boq.update",

  "project_bill.read",
  "project_bill.create",
  "project_bill.update",
  "project_bill.submit",
  "project_bill.certify",
  "project_bill.cancel",

  "challan_submission.read",
  "challan_submission.create",
  "challan_submission.update",
  "challan_submission.submit",
  "challan_submission.review",
  "challan_submission.approve",
  "challan_submission.reject",
  "challan_submission.release_payment",
  "challan_submission.cancel",

  "vat_tax_certificate.read",
  "vat_tax_certificate.create",
  "vat_tax_certificate.update",
  "vat_tax_certificate.export",

  "retention.read",
  "retention.release",

  "completion_certificate.read",
  "completion_certificate.create",
  "completion_certificate.update",
  "completion_certificate.submit",
  "completion_certificate.approve",
  "dlp.read",
  "dlp.manage",
  "defect.read",
  "defect.manage",
  "defect.create",
  "defect.update",
  "defect.verify",
  "retention_release.read",
  "retention_release.create",
  "retention_release.approve",
  "handover.read",
  "handover.manage",
  "handover.create",
  "handover.complete",
  "project_close.read",
  "project_close.close",
  "project_close.override",
  "project_close.reopen",
  "project_close.archive",

  "variation.read",
  "variation.create",
  "variation.update",
  "variation.submit",
  "variation.approve",

  "time_extension.read",
  "time_extension.create",
  "time_extension.update",
  "time_extension.submit",
  "time_extension.approve",

  "expense.create",
  "expense.read",
  "expense.approve",

  "project_expense.read",
  "project_expense.create",
  "project_expense.update",
  "project_expense.delete",
  "project_expense.export",

  "work_iou.read",
  "work_iou.create",
  "work_iou.update",
  "work_iou.submit",
  "work_iou.cancel",
  "work_iou.attachment",

  "receipt.create",
  "receipt.read",

  "cash_bank.read",
  "cash_bank.create",
  "bank_account.read",
  "bank_account.create",
  "bank_account.update",
  "bank_transfer.read",
  "bank_transfer.create",
  "financial_transaction.read",
  "financial_transaction.export",
  "bank_reconciliation.read",
  "bank_reconciliation.manage",
  "cheque.read",
  "cheque.create",
  "cheque.update",

  "accounts.read",
  "chart_of_accounts.read",
  "chart_of_accounts.create",
  "chart_of_accounts.update",
  "journal.read",
  "journal.create",
  "journal.post",
  "journal.reverse",
  "ledger.read",
  "receivable.read",
  "receivable.manage",
  "payable.read",
  "payable.manage",
  "project_accounts.read",
  "party_ledger.read",
  "opening_balance.read",
  "opening_balance.manage",

  "report.view",
  "report.export",

  "reminders.read",
  "reminders.create",
  "reminders.update",
  "reminders.complete",
  "reminders.cancel",

  "notifications.read",

  "documents.read",
  "documents.upload",
  "documents.update",
  "documents.archive",
  "documents.download",

  "user.manage",
  "role.manage",
  "settings.read",
  "settings.manage",

  "billing.view",
  "billing.manage",
  "billing.invoice.view",

  "masters.read",

  "vendor.read",
  "vendor.create",
  "vendor.update",
  "vendor.archive",

  "subcontractor.read",
  "subcontractor.create",
  "subcontractor.update",
  "subcontractor.archive",

  "item.read",
  "item.create",
  "item.update",
  "item.archive",

  "uom.manage",
  "payment_terms.manage",

  "procurement.read",

  "pr.create",
  "pr.update",
  "pr.submit",
  "pr.approve",

  "rfq.create",
  "rfq.update",
  "rfq.issue",

  "quotation.create",
  "quotation.update",

  "sales_quotation.read",
  "sales_quotation.create",
  "sales_quotation.update",
  "sales_quotation.send",
  "sales_quotation.result",
  "sales_quotation.follow_up",
  "sales_quotation.export",

  "cs.create",
  "cs.evaluate",
  "cs.approve",

  "po.create",
  "po.update",
  "po.approve",
  "po.issue",

  "grn.create",
  "grn.update",
  "grn.approve",

  "supplier_bill.read",
  "supplier_bill.create",
  "supplier_bill.update",
  "supplier_bill.submit",
  "supplier_bill.approve",
  "supplier_bill.cancel",

  "supplier_payment.read",
  "supplier_payment.create",
  "supplier_payment.cancel",

  "supplier_ledger.read",
] as const;

export type Permission = (typeof PERMISSIONS)[number];
