"use client";

import * as React from "react";
import { Check, Plus, X } from "lucide-react";
import { useCreateEmployeeLoan, useCreateExpenseClaim, useCreateLeaveRequest, useHrCommand, useHrEmployees, useHrExpenseClaims, useHrLeaveRequests, useHrLeaveTypes, useHrLoans } from "@bizovix/api-client";
import { FormField, PrimaryButton, SecondaryButton, SelectInput, TextInput } from "@bizovix/ui";
import { useSetBreadcrumb } from "@/components/providers/BreadcrumbContext";

const today = () => new Date().toISOString().slice(0, 10);
const money = (value: string | number) => Number(value).toLocaleString("en-US", { minimumFractionDigits: 2, maximumFractionDigits: 2 });
const label = (value: string) => value.replaceAll("_", " ").replace(/\b\w/g, (letter) => letter.toUpperCase());

export function HrLeaveFinanceWorkspace() {
  useSetBreadcrumb([{ label: "HR & Payroll", href: "/hr-payroll" }, { label: "Leave, Claims & Loans" }]);
  const employees = useHrEmployees(), types = useHrLeaveTypes(), leaves = useHrLeaveRequests(), claims = useHrExpenseClaims(), loans = useHrLoans();
  const createLeave = useCreateLeaveRequest(), createClaim = useCreateExpenseClaim(), createLoan = useCreateEmployeeLoan(), command = useHrCommand();
  const [notice, setNotice] = React.useState("");
  const [leaveType, setLeaveType] = React.useState({ name: "", daysPerYear: "" });
  const [leave, setLeave] = React.useState({ employeeId: "", leaveTypeId: "", startDate: today(), endDate: today(), reason: "" });
  const [claim, setClaim] = React.useState({ employeeId: "", category: "OTHER", amount: "", expenseDate: today(), description: "" });
  const [loan, setLoan] = React.useState({ employeeId: "", loanType: "LOAN", principalAmount: "", applicationDate: today(), reason: "" });
  const [repayment, setRepayment] = React.useState<Record<string, string>>({});
  const employeeOptions = (employees.data ?? []).map((row) => ({ value: row.id, label: `${row.employeeCode} - ${row.name}` }));

  async function run(action: () => Promise<unknown>, success: string) {
    try { await action(); setNotice(success); }
    catch (error) { setNotice(error instanceof Error ? error.message : "Action failed."); }
  }
  async function saveType(event: React.FormEvent) { event.preventDefault(); await run(() => command.mutateAsync({ path: "leave-types", body: { name: leaveType.name, daysPerYear: Number(leaveType.daysPerYear) } }), "Leave type saved."); setLeaveType({ name: "", daysPerYear: "" }); }
  async function saveLeave(event: React.FormEvent) { event.preventDefault(); await run(() => createLeave.mutateAsync(leave), "Leave request created."); }
  async function saveClaim(event: React.FormEvent) { event.preventDefault(); await run(() => createClaim.mutateAsync({ ...claim, amount: Number(claim.amount) }), "Expense claim created."); setClaim({ ...claim, amount: "", description: "" }); }
  async function saveLoan(event: React.FormEvent) { event.preventDefault(); await run(() => createLoan.mutateAsync({ ...loan, principalAmount: Number(loan.principalAmount) }), "Loan or advance request created."); setLoan({ ...loan, principalAmount: "", reason: "" }); }
  async function repay(id: string) { const amount = Number(repayment[id]); if (!amount) return; await run(() => command.mutateAsync({ path: `employee-loans/${id}/repayments`, body: { amount, paidDate: today() } }), "Repayment recorded."); setRepayment((current) => ({ ...current, [id]: "" })); }

  return <div className="space-y-4">
    <div><h1 className="text-page-title text-biz-text">Leave, Claims & Loans</h1><p className="mt-1 text-sm text-biz-muted">Separate approval workflows for time off, employee reimbursement and advances</p></div>
    {notice && <div className="rounded-md border border-blue-200 bg-blue-50 px-4 py-2 text-sm text-biz-blue">{notice}</div>}
    <div className="grid gap-4 xl:grid-cols-2">
      <section className="rounded-lg border border-biz-border bg-white p-4"><h2 className="font-bold">Leave Setup & Request</h2><form onSubmit={saveType} className="mt-3 grid gap-2 sm:grid-cols-3"><TextInput placeholder="Leave type" value={leaveType.name} onChange={(event) => setLeaveType({ ...leaveType, name: event.target.value })} required /><TextInput type="number" min="0" placeholder="Days / year" value={leaveType.daysPerYear} onChange={(event) => setLeaveType({ ...leaveType, daysPerYear: event.target.value })} required /><SecondaryButton type="submit"><Plus className="h-4 w-4" /> Add Type</SecondaryButton></form><form onSubmit={saveLeave} className="mt-4 grid gap-3 sm:grid-cols-2"><FormField label="Employee"><SelectInput value={leave.employeeId} onChange={(event) => setLeave({ ...leave, employeeId: event.target.value })} options={employeeOptions} required /></FormField><FormField label="Leave Type"><SelectInput value={leave.leaveTypeId} onChange={(event) => setLeave({ ...leave, leaveTypeId: event.target.value })} options={(types.data ?? []).map((row) => ({ value: row.id, label: `${row.name} (${row.daysPerYear} days)` }))} required /></FormField><FormField label="From"><TextInput type="date" value={leave.startDate} onChange={(event) => setLeave({ ...leave, startDate: event.target.value })} /></FormField><FormField label="To"><TextInput type="date" min={leave.startDate} value={leave.endDate} onChange={(event) => setLeave({ ...leave, endDate: event.target.value })} /></FormField><FormField label="Reason"><TextInput value={leave.reason} onChange={(event) => setLeave({ ...leave, reason: event.target.value })} /></FormField><div className="flex items-end"><PrimaryButton type="submit">Request Leave</PrimaryButton></div></form></section>
      <section className="rounded-lg border border-biz-border bg-white p-4"><h2 className="font-bold">Employee Expense Claim</h2><form onSubmit={saveClaim} className="mt-3 grid gap-3 sm:grid-cols-2"><FormField label="Employee"><SelectInput value={claim.employeeId} onChange={(event) => setClaim({ ...claim, employeeId: event.target.value })} options={employeeOptions} required /></FormField><FormField label="Category"><SelectInput value={claim.category} onChange={(event) => setClaim({ ...claim, category: event.target.value })} options={["TRAVEL", "MEAL", "TRANSPORTATION", "ACCOMMODATION", "OTHER"].map((value) => ({ value, label: label(value) }))} /></FormField><FormField label="Amount"><TextInput type="number" min="0.01" step="0.01" value={claim.amount} onChange={(event) => setClaim({ ...claim, amount: event.target.value })} required /></FormField><FormField label="Expense Date"><TextInput type="date" value={claim.expenseDate} onChange={(event) => setClaim({ ...claim, expenseDate: event.target.value })} /></FormField><FormField label="Description"><TextInput value={claim.description} onChange={(event) => setClaim({ ...claim, description: event.target.value })} /></FormField><div className="flex items-end"><PrimaryButton type="submit">Submit Claim</PrimaryButton></div></form><p className="mt-3 text-xs text-biz-muted">Claims remain an HR reimbursement workflow and are not auto-posted as General Expenses.</p></section>
      <section className="rounded-lg border border-biz-border bg-white p-4 xl:col-span-2"><h2 className="font-bold">Employee Loan / Advance</h2><form onSubmit={saveLoan} className="mt-3 grid gap-3 md:grid-cols-5"><FormField label="Employee"><SelectInput value={loan.employeeId} onChange={(event) => setLoan({ ...loan, employeeId: event.target.value })} options={employeeOptions} required /></FormField><FormField label="Type"><SelectInput value={loan.loanType} onChange={(event) => setLoan({ ...loan, loanType: event.target.value })} options={["LOAN", "SALARY_ADVANCE", "EXPENSE_ADVANCE"].map((value) => ({ value, label: label(value) }))} /></FormField><FormField label="Principal"><TextInput type="number" min="0.01" value={loan.principalAmount} onChange={(event) => setLoan({ ...loan, principalAmount: event.target.value })} required /></FormField><FormField label="Application Date"><TextInput type="date" value={loan.applicationDate} onChange={(event) => setLoan({ ...loan, applicationDate: event.target.value })} /></FormField><div className="flex items-end"><PrimaryButton type="submit">Submit Request</PrimaryButton></div></form></section>
    </div>
    <div className="grid gap-4 xl:grid-cols-3">
      <section className="rounded-lg border border-biz-border bg-white p-4"><h2 className="font-bold">Leave Requests</h2>{!(leaves.data?.length) ? <p className="mt-3 text-xs text-biz-muted">No leave requests.</p> : leaves.data.map((row) => <div key={row.id} className="mt-3 border-t pt-3 text-xs"><div className="flex justify-between"><b>{row.employee.name}</b><span>{row.status}</span></div><p>{row.leaveType.name} · {new Date(row.startDate).toLocaleDateString()}–{new Date(row.endDate).toLocaleDateString()}</p>{row.status === "PENDING" && <div className="mt-2 flex gap-3"><button className="text-biz-blue" onClick={() => command.mutate({ path: `leave-requests/${row.id}/approve`, method: "PATCH" })}><Check className="inline h-3.5 w-3.5" /> Approve</button><button className="text-red-600" onClick={() => command.mutate({ path: `leave-requests/${row.id}/reject`, method: "PATCH", body: { note: "Rejected from HR review" } })}><X className="inline h-3.5 w-3.5" /> Reject</button></div>}</div>)}</section>
      <section className="rounded-lg border border-biz-border bg-white p-4"><h2 className="font-bold">Expense Claims</h2>{!(claims.data?.length) ? <p className="mt-3 text-xs text-biz-muted">No claims.</p> : claims.data.map((row) => <div key={row.id} className="mt-3 border-t pt-3 text-xs"><div className="flex justify-between"><b>{row.employee.name}</b><span>{row.status}</span></div><p>{label(row.category)} · ৳ {money(row.amount)}</p><div className="mt-2 flex gap-3">{row.status === "PENDING" && <button className="text-biz-blue" onClick={() => command.mutate({ path: `expense-claims/${row.id}/approve`, method: "PATCH" })}>Approve</button>}{row.status === "APPROVED" && <button className="text-biz-blue" onClick={() => command.mutate({ path: `expense-claims/${row.id}/mark-reimbursed`, method: "PATCH" })}>Mark Reimbursed</button>}</div></div>)}</section>
      <section className="rounded-lg border border-biz-border bg-white p-4"><h2 className="font-bold">Loans & Advances</h2>{!(loans.data?.length) ? <p className="mt-3 text-xs text-biz-muted">No loan requests.</p> : loans.data.map((row) => <div key={row.id} className="mt-3 border-t pt-3 text-xs"><div className="flex justify-between"><b>{row.employee.name}</b><span>{row.status}</span></div><p>{label(row.loanType)} · Balance ৳ {money(row.remainingBalance)}</p><div className="mt-2 flex flex-wrap gap-2">{row.status === "PENDING" && <button className="text-biz-blue" onClick={() => command.mutate({ path: `employee-loans/${row.id}/approve`, method: "PATCH" })}>Approve</button>}{row.status === "APPROVED" && <button className="text-biz-blue" onClick={() => command.mutate({ path: `employee-loans/${row.id}/disburse`, method: "PATCH" })}>Disburse</button>}{["DISBURSED", "APPROVED"].includes(row.status) && Number(row.remainingBalance) > 0 && <div className="flex gap-1"><TextInput type="number" min="0.01" max={Number(row.remainingBalance)} className="h-7 w-24" placeholder="Repayment" value={repayment[row.id] ?? ""} onChange={(event) => setRepayment({ ...repayment, [row.id]: event.target.value })} /><button className="text-biz-blue" onClick={() => repay(row.id)}>Post</button></div>}</div></div>)}</section>
    </div>
  </div>;
}
