export const queryKeys = {
  me: ["auth", "me"] as const,
  dashboard: (params?: unknown) => ["dashboard", params ?? {}] as const,
  organizations: (search?: string) => ["organizations", search ?? ""] as const,
  bankAccounts: ["bank-accounts"] as const,
  tenders: (params?: unknown) => ["tenders", params ?? {}] as const,
  tender: (id: string) => ["tenders", id] as const,
  tenderStats: ["tenders", "stats"] as const,
  tenderCategories: ["tenders", "categories"] as const,
  tenderOptions: ["tenders", "options"] as const,
  tenderCostings: (params?: unknown) => ["tender-costings", "list", params ?? {}] as const,
  tenderCosting: (id: string) => ["tender-costings", "one", id] as const,
  tenderCostingStats: ["tender-costings", "stats"] as const,
  itemPriceHistory: ["tender-costings", "item-price-history"] as const,
  documents: (params?: unknown) => ["documents", params ?? {}] as const,
  document: (id: string) => ["documents", id] as const,
  documentCategories: ["documents", "categories"] as const,
  documentPurchases: (params?: unknown) => ["document-purchases", params ?? {}] as const,
  documentPurchaseRequests: (params?: unknown) => ["document-purchase-requests", params ?? {}] as const,
  documentPurchaseRequestStats: ["document-purchase-requests", "stats"] as const,
  documentPurchaseStats: ["document-purchases", "stats"] as const,
  documentPurchase: (id: string) => ["document-purchases", id] as const,
  tenderSecurityPending: (params?: unknown) => ["tender-securities", "pending", params ?? {}] as const,
  tenderSecurities: ["tender-securities"] as const,
  creditCommitmentPending: (params?: unknown) => ["credit-commitments", "pending", params ?? {}] as const,
  creditCommitments: (params?: unknown) => ["credit-commitments", params ?? {}] as const,
  creditCommitment: (id: string) => ["credit-commitments", id] as const,
  pgBgEligible: (params?: unknown) => ["pg-bg", "eligible", params ?? {}] as const,
  pgBgWorkflowByDocument: (id: string) => ["pg-bg", "workflow", "document", id] as const,
  workCategories: ["pg-bg", "work-categories"] as const,
  organizationContacts: (organizationMasterId?: string) => ["pg-bg", "contacts", organizationMasterId ?? ""] as const,
  cmsWorks: (params?: unknown) => ["cms-works", params ?? {}] as const,
  cmsWork: (id: string) => ["cms-works", id] as const,
  cmsWorkStats: (status = "ONGOING") => ["cms-works", "stats", status] as const,
  cmsWorkCategories: ["cms-works", "categories"] as const,
  contracts: (params?: unknown) => ["contracts", params ?? {}] as const,
  contract: (id: string) => ["contracts", id] as const,
  contractStats: ["contracts", "stats"] as const,
  contractCategories: ["contracts", "categories"] as const,
  projectBudgets: (workId: string) => ["cms-works", workId, "budgets"] as const,
  projectBudgetSummary: (workId: string) => ["cms-works", workId, "budget-summary"] as const,
  budgetVsActual: (workId: string) => ["cms-works", workId, "budget-vs-actual"] as const,
  boqItems: (workId: string) => ["cms-works", workId, "boq"] as const,
  boqSummary: (workId: string) => ["cms-works", workId, "boq-summary"] as const,
  projectProgress: (workId: string) => ["cms-works", workId, "progress"] as const,
  projectBills: (params?: unknown) => ["project-bills", params ?? {}] as const,
  projectBill: (id: string) => ["project-bills", id] as const,
  projectBillStats: (cmsWorkId?: string) => ["project-bills", "stats", cmsWorkId ?? ""] as const,
  challanSubmissions: (params?: unknown) => ["challan-submissions", params ?? {}] as const,
  challanSubmission: (id: string) => ["challan-submissions", id] as const,
  challanSubmissionStats: (cmsWorkId?: string) => ["challan-submissions", "stats", cmsWorkId ?? ""] as const,
  challanSubmissionNumberPreview: ["challan-submissions", "number-preview"] as const,
  vatTaxCertificates: (params?: unknown) => ["vat-tax-certificates", params ?? {}] as const,
  vatTaxCertificate: (id: string) => ["vat-tax-certificates", id] as const,
  vatTaxCertificateStats: (params?: unknown) => ["vat-tax-certificates", "stats", params ?? {}] as const,
  vatTaxCertificateRecent: (params?: unknown) => ["vat-tax-certificates", "recent", params ?? {}] as const,
  workCompletionCertificates: (params?: unknown) => ["work-completion-certificates", params ?? {}] as const,
  workCompletionCertificate: (workId: string) => ["work-completion-certificates", workId] as const,
  workCompletionCertificateStats: (params?: unknown) => ["work-completion-certificates", "stats", params ?? {}] as const,
  variationOrders: (cmsWorkId?: string) => ["variation-orders", cmsWorkId ?? ""] as const,
  variationOrder: (id: string) => ["variation-orders", id] as const,
  timeExtensions: (cmsWorkId?: string) => ["time-extensions", cmsWorkId ?? ""] as const,
  timeExtension: (id: string) => ["time-extensions", id] as const,
  deductionConfigs: (type?: string) => ["deduction-configs", type ?? ""] as const,
  projectExpenses: (params?: unknown) => ["project-expenses", params ?? {}] as const,
  projectExpenseHeads: ["project-expenses", "expense-heads"] as const,
  projectExpensePeople: ["project-expenses", "people"] as const,
  generalExpenses: (params?: unknown) => ["general-expenses", params ?? {}] as const,
  workIous: (params?: unknown) => ["work-ious", "list", params ?? {}] as const,
  workIou: (id: string) => ["work-ious", "one", id] as const,
  workIouOptions: ["work-ious", "options"] as const,
  receipts: (params?: unknown) => ["receipts", params ?? {}] as const,
  receiptSummary: ["receipts", "summary"] as const,
  activityLogs: (params?:unknown) => ["activity-logs",params??{}] as const,
  activityLogStats: ["activity-logs","stats"] as const,
  organizationMasters: (params?: unknown) => ["organizations", "all", params ?? {}] as const,
  parties: (params?: unknown) => ["parties", params ?? {}] as const,
  party: (id: string) => ["parties", id] as const,
  partyStats: (roles?: string) => ["parties", "stats", roles ?? ""] as const,
  masterCategories: (type?: string) => ["master-categories", type ?? ""] as const,
  uoms: ["uoms"] as const,
  paymentTerms: ["payment-terms"] as const,
  items: (params?: unknown) => ["items", params ?? {}] as const,
  item: (id: string) => ["items", id] as const,
  itemStats: ["items", "stats"] as const,
  purchaseRequisitions: (params?: unknown) => ["purchase-requisitions", params ?? {}] as const,
  purchaseRequisition: (id: string) => ["purchase-requisitions", id] as const,
  purchaseRequisitionStats: ["purchase-requisitions", "stats"] as const,
  rfqs: (params?: unknown) => ["rfqs", params ?? {}] as const,
  rfq: (id: string) => ["rfqs", id] as const,
  rfqStats: ["rfqs", "stats"] as const,
  supplierQuotations: (params?: unknown) => ["supplier-quotations", params ?? {}] as const,
  supplierQuotation: (id: string) => ["supplier-quotations", id] as const,
  comparativeStatements: ["comparative-statements"] as const,
  comparativeStatement: (id: string) => ["comparative-statements", id] as const,
  comparativeStatementStats: ["comparative-statements", "stats"] as const,
  comparativeStatementItemComparison: (id: string) => ["comparative-statements", id, "item-comparison"] as const,
  purchaseOrders: (params?: unknown) => ["purchase-orders", params ?? {}] as const,
  purchaseOrder: (id: string) => ["purchase-orders", id] as const,
  purchaseOrderStats: ["purchase-orders", "stats"] as const,
  grns: (params?: unknown) => ["grns", params ?? {}] as const,
  grn: (id: string) => ["grns", id] as const,
  grnStats: ["grns", "stats"] as const,
  supplierBills: (params?: unknown) => ["supplier-bills", params ?? {}] as const,
  supplierBill: (id: string) => ["supplier-bills", id] as const,
  supplierBillStats: ["supplier-bills", "stats"] as const,
  billableLines: (purchaseOrderId: string) => ["supplier-bills", "billable-lines", purchaseOrderId] as const,
  supplierPayments: (params?: unknown) => ["supplier-payments", params ?? {}] as const,
  supplierPayment: (id: string) => ["supplier-payments", id] as const,
  supplierPaymentStats: ["supplier-payments", "stats"] as const,
  supplierLedger: (params?: unknown) => ["supplier-ledger", params ?? {}] as const,
  apAging: (params?: unknown) => ["supplier-ledger", "aging", params ?? {}] as const,
  apReconciliation: ["supplier-ledger", "reconciliation"] as const,
  salesQuotations: (params?: unknown) => ["sales-quotations", "list", params ?? {}] as const,
  salesQuotation: (id: string) => ["sales-quotations", "one", id] as const,
  salesQuotationSummary: (params?: unknown) => ["sales-quotations", "summary", params ?? {}] as const,
  salesQuotationRecent: (params?: unknown) => ["sales-quotations", "recent", params ?? {}] as const,
  salesQuotationCostingSummary: (params?: unknown) => ["sales-quotations", "costing-summary", params ?? {}] as const,
  salesQuotationRecentDecisions: (params?: unknown) => ["sales-quotations", "recent-decisions", params ?? {}] as const,
  salesQuotationOptions: ["sales-quotations", "options"] as const,
  salesQuotationCosting: (id: string) => ["sales-quotations", "one", id, "costing"] as const,
  salesQuotationResults: (params?: unknown) => ["sales-quotations", "results", "list", params ?? {}] as const,
  salesQuotationResultSummary: (params?: unknown) => ["sales-quotations", "results", "summary", params ?? {}] as const,
  salesQuotationFollowUps: (id: string, params?: unknown) => ["sales-quotations", "one", id, "follow-ups", params ?? {}] as const,
};
