export const queryKeys = {
  me: ["auth", "me"] as const,
  dashboard: ["dashboard"] as const,
  organizations: (search?: string) => ["organizations", search ?? ""] as const,
  bankAccounts: ["bank-accounts"] as const,
  documentPurchases: (params?: unknown) => ["document-purchases", params ?? {}] as const,
  documentPurchaseStats: ["document-purchases", "stats"] as const,
  documentPurchase: (id: string) => ["document-purchases", id] as const,
  tenderSecurityPending: (params?: unknown) => ["tender-securities", "pending", params ?? {}] as const,
  tenderSecurities: ["tender-securities"] as const,
  creditCommitmentPending: (params?: unknown) => ["credit-commitments", "pending", params ?? {}] as const,
  creditCommitments: (params?: unknown) => ["credit-commitments", params ?? {}] as const,
  creditCommitment: (id: string) => ["credit-commitments", id] as const,
  pgBgEligible: (params?: unknown) => ["pg-bg", "eligible", params ?? {}] as const,
  pgBgWorkflowByDocument: (id: string) => ["pg-bg", "workflow", "document", id] as const,
  workCategories: ["pg-bg", "work-categories"] as const,
  organizationContacts: (organizationMasterId?: string) => ["pg-bg", "contacts", organizationMasterId ?? ""] as const,
  cmsWorks: (params?: unknown) => ["cms-works", params ?? {}] as const,
  cmsWork: (id: string) => ["cms-works", id] as const,
  cmsWorkStats: ["cms-works", "stats"] as const,
  cmsWorkCategories: ["cms-works", "categories"] as const,
};
